---
- name: Provision EC2 instances
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Launch EC2 instance
      ec2:
        key_name: Ansible AWS IaC
        instance_type: t2.micro
        image: ami-0406d1fdd021121cd
        wait: yes
        region: us-west-2
        group: my-security-group
        count: 2
      register: ec2
