---
- name: Provision EC2 instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: "Ansible AWS IaC"
        instance_type: "t2.micro"
        image_id: "ami-0406d1fdd021121cd"  
        region: "us-west-2"
        wait: true
        count: 1
        security_groups:
          - "my-security-group"
        tags:
          Name: "my_instance"
      register: ec2
