---
- name: Install software on EC2 instances
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Apache
      apt:
        name: apache2
        state: present
