---
- name: Create S3 bucket and RDS instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: my-unique-bucket-3  # Ensure this name is globally unique
        state: present
        region: us-east-1
      register: s3_result

    - name: Create RDS instance
      community.aws.rds_instance:
        db_instance_identifier: my-rds-instance
        db_name: mydb
        engine: mysql
        master_username: myuser
        master_user_password: mypassword
        db_instance_class: db.t3.micro
        allocated_storage: 20
        state: present
        region: us-east-1
        # Remove the following lines if your AWS credentials are set up in the environment
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: rds_result

    - name: Check RDS instance status
      community.aws.rds_instance:
        db_instance_identifier: my-rds-instance
        region: us-east-1
      register: rds_status
      retries: 10
      delay: 30
      until: rds_status.instances[0].db_instance_status == 'available'
      when: rds_result is defined and rds_result.changed
