---
- name: Manage S3 and RDS
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create S3 bucket
      aws_s3:
        bucket: my-bucket-unique-name
        mode: create
        region: eu-north-1
    - name: Create RDS instance
      rds:
        command: create
        instance_name: mydb
        db_name: mydatabase
        engine: mysql
        size: 5
        instance_type: db.t2.micro
        username: admin
        password: password123
        region: eu-north-1
