---
- name: Create S3 bucket and RDS instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Generate a unique bucket name
      set_fact:
        s3_bucket_name: "my-unique-bucket-{{ 99999 | random }}"

    - name: Debug generated bucket name
      debug:
        msg: "Using bucket name: {{ s3_bucket_name }}"

    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket_name }}"
        state: present
        region: us-east-1
      register: s3_result

    - name: Create RDS instance
      community.aws.rds_instance:
        db_instance_identifier: my-rds-instance
        db_name: mydb
        engine: mysql
        master_username: myuser
        master_user_password: mypassword
        db_instance_class: db.t3.micro
        allocated_storage: 20
        state: present
        region: us-east-1
      register: rds_result

    - name: Debug RDS creation result
      debug:
        var: rds_result

    - name: Check RDS instance status
      community.aws.rds_instance:
        db_instance_identifier: my-rds-instance
        region: us-east-1
      register: rds_status
      retries: 10
      delay: 30
      until: >
        rds_status.db_instance.db_instance_status == 'available'
      when: rds_result is defined and rds_result.changed

    - name: Debug RDS status
      debug:
        var: rds_status
