---
- name: Configure security groups
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: my-security-group
        description: My security group
        region: us-east-1  
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
        state: present
